SmartRide/Controllers/TrackingController.cs
using Microsoft.AspNetCore.Mvc;
using SmartRide.Data;
using SmartRide.Models;

namespace SmartRide.Controllers
{
    public class TrackingController : Controller
    {
        public readonly ApplicationDbContext context;

        public TrackingController(ApplicationDbContext _context)
        {
            context = _context;
        }

        public IActionResult Index(string custName, string phoneNumber, int rideId)
        {
            var model = new CustInfo
            {
                customerName = custName ?? "Unknown",
                phoneNumber = phoneNumber ?? "No phone number available",
                rideId = rideId
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Complete(int rideId)
        {
            var ride = context.Rides.Find(rideId);
            ride.status = "Completed";
            context.Rides.Update(ride);
            context.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public IActionResult Arrived(int rideId)
        {
            var ride = context.Rides.Find(rideId);
            ride.DropOffTime = DateTime.Now;
            context.Rides.Update(ride);
            context.SaveChanges();
            return RedirectToAction("Index", "Payment", new { rideId = rideId});
        }
    }
}

SmartRide/Views/Tracking/Index.cshtml
@model CustInfo
@{
    Layout = "_DriverTrackLayout";
    ViewData["Title"] = "Track";
}
<h1>Tracking Customer</h1>

<div id="map" style="height:180px"></div>

<div class="col-lg-4 col-12 m-auto p-1">
    <div class="border p-2 m-auto">
        <p>Customer Name : @Model.customerName</p>
        <p>Customer Phone Number : @Model.phoneNumber</p>
        <p id="time">Time : Loading..</p>
        <p id="distance">Distance : Loading..</p>
        
        <input type="hidden" id="vehicleType" value="@User.FindFirst("VehicleType")?.Value" />
        <div>
            <div class="m-1">
                <button class="btn btn-primary m-1" onclick="completePickup(event)">Complete pickup</button>
            </div>

            <div class="m-1">
                <form asp-controller="Tracking" asp-action="Complete">
                    <input type="hidden" id="rideId" name="rideId" value="@Model.rideId" />
                    <button type="submit" class="btn btn-danger m-1" onclick="completeDropoff(event)">Complete Ride</button>
                </form>
            </div>
        </div>
        
    </div>
</div>